version: '3'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      setup:
        condition: service_completed_successfully
 
  setup:
    build:
      context: .
      dockerfile: Dockerfile.setup
    depends_on:
      - timescaledb

networks:
  timescalenet:
    driver: bridge

